version: '3'

networks:
  proxy:
    driver: bridge

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
    ports:
      - 80:80
    networks:
      - proxy
  
  web-blue-01:
    image: fabricioveronez/web-page:blue
    networks:
      - proxy
  # replica de balanciamento 
  web-blue-02:
    image: fabricioveronez/web-page:blue
    networks:
      - proxy

  web-green-01:
    image: fabricioveronez/web-page:green
    networks:
      - proxy
  # replica de balanciamento 
  web-green-02:
    image: fabricioveronez/web-page:green
    networks:
      - proxy